"use client";

import { createContext, createElement, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Language = "en" | "zh" | "ja" | "ko" | "es" | "fr" | "ar";

type Translation = {
  languageName: string;
  nav: {
    dashboard: string;
    nodes: string;
    whyEv: string;
    highlights: string;
    revenue: string;
    network: string;
    payment: string;
  };
  hero: {
    title: string;
    subtitle: string;
    invest: string;
    deployment: string;
  };
  immersive: {
    stationTitle: string;
    stationSubtitle: string;
    assetsTitle: string;
    assetsSubtitle: string;
  };
  revenue: {
    title: string;
    subtitle: string;
    steps: string[];
  };
  infrastructure: {
    title: string;
    subtitle: string;
    items: { title: string; description: string }[];
  };
  deployment: {
    title: string;
    subtitle: string;
    overview: string[];
    selectedMarket: string;
    planned: string;
    active: string;
    utilization: string;
    phase: string;
    markets: string;
    disclaimer: string;
  };
  why: {
    eyebrow: string;
    title: string;
    items: { title: string; description: string }[];
  };
  features: {
    eyebrow: string;
    title: string;
    items: { title: string; description: string }[];
  };
  payment: {
    eyebrow: string;
    title: string;
    subtitle: string;
    baseRule: string;
    fullNode: string;
    allocation: string;
    referenceValue: string;
    allocationSelector: string;
    summary: string;
    ethEstimate: string;
    ethEstimateLive: string;
    disclaimer: string;
    panel: string;
    wallet: string;
    network: string;
    asset: string;
    qrAmount: string;
    receiver: string;
    product: string;
  };
  flow: {
    eyebrow: string;
    title: string;
    steps: { title: string; description: string }[];
  };
  footer: {
    brand: string;
    disclosure: string;
    mvp: string;
  };
  dashboard: {
    title: string;
    subtitle: string;
    connectedWallet: string;
    notConnected: string;
    portfolio: string;
    totalAllocation: string;
    participationValue: string;
    activeStations: string;
    monthlySessions: string;
    allocationTitle: string;
    allocationSubtitle: string;
    revenueTitle: string;
    revenueItems: string[];
    exposureTitle: string;
    activityTitle: string;
    activityItems: { label: string; value: string }[];
    transactionsTitle: string;
    transactionHeaders: string[];
    disclaimer: string;
  };
};

export const languages: { code: Language; label: string }[] = [
  { code: "en", label: "English" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "ar", label: "العربية" },
];

const en: Translation = {
  languageName: "English",
  nav: {
    dashboard: "Dashboard",
    nodes: "Nodes",
    whyEv: "Why EV",
    highlights: "Highlights",
    revenue: "Revenue",
    network: "Network",
    payment: "Payment",
  },
  hero: {
    title: "Invest in EV Charging Infrastructure",
    subtitle: "Revenue-sharing nodes backed by real-world deployment.",
    invest: "Invest Now",
    deployment: "View Deployment",
  },
  immersive: {
    stationTitle: "Real Charging Infrastructure",
    stationSubtitle: "Physical EV charging stations deployed in real-world locations.",
    assetsTitle: "Revenue-Sharing Energy Assets",
    assetsSubtitle:
      "Node holders participate in charging service revenue generated by deployed stations.",
  },
  revenue: {
    title: "How Revenue Sharing Works",
    subtitle:
      "Revenue is generated from real-world EV charging activity across deployed stations.",
    steps: [
      "Charging stations are deployed in offline locations.",
      "EV drivers pay for charging sessions.",
      "Platform collects charging service revenue.",
      "Revenue is allocated to node holders.",
    ],
  },
  infrastructure: {
    title: "Infrastructure Overview",
    subtitle:
      "CyberCharge nodes are linked to deployed shared EV charging infrastructure designed for high-utilization urban environments.",
    items: [
      {
        title: "Urban Deployment",
        description:
          "Designed for parking facilities, mixed-use commercial zones, and high-density charging demand areas.",
      },
      {
        title: "Shared Utilization",
        description:
          "Infrastructure is optimized for recurring charging activity across shared-access environments.",
      },
      {
        title: "Infrastructure-backed Model",
        description:
          "Revenue participation is tied to charging service activity generated by deployed stations.",
      },
    ],
  },
  deployment: {
    title: "Deployment Network",
    subtitle:
      "Real-world charging station deployment maps across high-density EV infrastructure markets.",
    overview: [
      "Planned Sites",
      "Active Stations",
      "Deployment Markets",
      "Avg. Estimated Utilization",
    ],
    selectedMarket: "Selected Market",
    planned: "Planned Sites",
    active: "Active Stations",
    utilization: "Estimated Utilization",
    phase: "Deployment Phase",
    markets: "Deployment Markets",
    disclaimer:
      "Deployment data is illustrative and subject to site acquisition, permitting, installation, and utilization activity.",
  },
  why: {
    eyebrow: "Market Context",
    title: "Why EV Infrastructure?",
    items: [
      {
        title: "EV adoption growth",
        description:
          "Long-term mobility demand is shifting toward electric fleets and private EVs.",
      },
      {
        title: "Charging demand expansion",
        description:
          "More vehicles on the road require more accessible local charging capacity.",
      },
      {
        title: "Offline infrastructure scalability",
        description:
          "Shared stations can be deployed across parking, retail, and community sites.",
      },
      {
        title: "Revenue-generating utility assets",
        description:
          "Charging infrastructure creates service revenue through real-world usage.",
      },
    ],
  },
  features: {
    eyebrow: "Investment Highlights",
    title: "Built around deployed energy infrastructure.",
    items: [
      {
        title: "Real-world Charging Assets",
        description: "Backed by physical EV charging stations deployed offline.",
      },
      {
        title: "Revenue Sharing Model",
        description: "Node holders receive a share of charging service revenue.",
      },
      {
        title: "Web3 Payment Access",
        description: "Purchase investment nodes with crypto through wallet or QR payment.",
      },
      {
        title: "Limited Deployment Round",
        description: "Early nodes are tied to the first batch of deployed stations.",
      },
    ],
  },
  payment: {
    eyebrow: "Investment Entry",
    title: "Infrastructure Allocation",
    subtitle:
      "Participate in revenue-sharing EV infrastructure through fractional allocation units backed by deployed charging stations.",
    baseRule: "Base Rule",
    fullNode: "1 Full Charging Node",
    allocation: "Infrastructure Allocation",
    referenceValue: "Reference Value",
    allocationSelector: "Allocation Selector",
    summary: "Estimated Allocation Summary",
    ethEstimate: "ETH estimate uses a live market conversion when available.",
    ethEstimateLive: "ETH estimate uses a live market conversion at approximately",
    disclaimer:
      "Revenue participation depends on infrastructure deployment and utilization activity.",
    panel: "Payment Panel",
    wallet: "Wallet",
    network: "Network",
    asset: "Payment Asset",
    qrAmount: "QR Amount",
    receiver: "Receiver Address",
    product: "Shared Infrastructure Allocation Unit",
  },
  flow: {
    eyebrow: "Investment Flow",
    title: "From wallet connection to node allocation.",
    steps: [
      {
        title: "Connect Wallet",
        description: "Authenticate with a supported Web3 wallet.",
      },
      {
        title: "Select Allocation",
        description: "Choose a fractional infrastructure allocation unit.",
      },
      {
        title: "Pay with Crypto",
        description: "Send ETH, USDT, or USDC through wallet or QR payment.",
      },
      {
        title: "Receive Allocation",
        description: "Receive MVP-stage allocation details for the selected node.",
      },
    ],
  },
  footer: {
    brand: "CyberCharge Node",
    disclosure:
      "This page is a front-end MVP. Revenue figures are illustrative and not financial guarantees. Always provide proper legal disclosures before accepting real investment funds.",
    mvp:
      "No backend, contract, order system, or automatic payment detection is included in this MVP. Projected utilization and deployment metrics are examples only.",
  },
  dashboard: {
    title: "Investor Dashboard",
    subtitle: "Monitor infrastructure allocation, deployment exposure, and network activity.",
    connectedWallet: "Connected Wallet",
    notConnected: "Connect a wallet to preview investor status.",
    portfolio: "Portfolio Overview",
    totalAllocation: "Total Infrastructure Allocation",
    participationValue: "Estimated Participation Value",
    activeStations: "Linked Active Stations",
    monthlySessions: "Estimated Monthly Sessions",
    allocationTitle: "Infrastructure Allocation",
    allocationSubtitle:
      "A fractional allocation profile linked to shared EV charging infrastructure deployment.",
    revenueTitle: "Revenue Participation",
    revenueItems: [
      "Projected Network Activity",
      "Revenue Participation",
      "Deployment Exposure",
      "Utilization-linked metrics",
    ],
    exposureTitle: "Deployment Exposure",
    activityTitle: "Network Activity",
    activityItems: [
      { label: "Recent Charging Activity", value: "4,920 sessions" },
      { label: "Peak Utilization Windows", value: "17:00-21:00" },
      { label: "Energy Delivered", value: "286 MWh" },
      { label: "Active Charging Bays", value: "1,184" },
    ],
    transactionsTitle: "Transaction History",
    transactionHeaders: ["Activity", "Network", "Amount", "Status"],
    disclaimer:
      "Dashboard metrics are illustrative until connected to verified operational and on-chain infrastructure data.",
  },
};

export const translations: Record<Language, Translation> = {
  en,
  zh: {
    ...en,
    languageName: "中文",
    nav: {
      dashboard: "仪表盘",
      nodes: "节点",
      whyEv: "为何选择 EV",
      highlights: "亮点",
      revenue: "收益模型",
      network: "网络",
      payment: "支付",
    },
    hero: {
      title: "投资电动汽车充电基础设施",
      subtitle: "由真实部署支持的收益参与型充电节点。",
      invest: "立即投资",
      deployment: "查看部署",
    },
    immersive: {
      stationTitle: "真实充电基础设施",
      stationSubtitle: "部署在真实线下场景中的实体电动汽车充电站。",
      assetsTitle: "收益参与型能源资产",
      assetsSubtitle: "节点持有人参与已部署充电站产生的充电服务收入分配。",
    },
    revenue: {
      title: "收益参与如何运作",
      subtitle: "收益来自已部署充电站的真实电动汽车充电活动。",
      steps: [
        "充电站部署在线下场地。",
        "电动车用户为充电服务付费。",
        "平台收取充电服务收入。",
        "收入按规则分配给节点持有人。",
      ],
    },
    infrastructure: {
      title: "基础设施概览",
      subtitle:
        "CyberCharge 节点关联已部署的共享电动汽车充电基础设施，面向高利用率城市环境设计。",
      items: [
        {
          title: "城市部署",
          description: "面向停车设施、复合商业区域和高密度充电需求区域设计。",
        },
        {
          title: "共享利用",
          description: "基础设施针对共享接入环境中的持续充电活动进行优化。",
        },
        {
          title: "基础设施支持模型",
          description: "收益参与与已部署站点产生的充电服务活动相关联。",
        },
      ],
    },
    deployment: {
      title: "部署网络",
      subtitle: "覆盖高密度电动汽车基础设施市场的真实充电站部署地图。",
      overview: ["计划场地", "运营站点", "部署市场", "平均预估利用率"],
      selectedMarket: "选定市场",
      planned: "计划场地",
      active: "运营站点",
      utilization: "预估利用率",
      phase: "部署阶段",
      markets: "部署市场",
      disclaimer: "部署数据为示例，取决于场地获取、许可、安装和实际利用活动。",
    },
    payment: {
      ...en.payment,
      eyebrow: "投资入口",
      title: "基础设施份额",
      subtitle: "通过由已部署充电站支持的分数化份额，参与电动汽车基础设施收入。",
      baseRule: "基础规则",
      fullNode: "1 个完整充电节点",
      allocation: "基础设施份额",
      referenceValue: "参考价值",
      allocationSelector: "份额选择",
      summary: "预估份额摘要",
      ethEstimate: "ETH 估算在可用时使用实时市场换算。",
      ethEstimateLive: "ETH 估算使用实时市场换算，约为",
      disclaimer: "收益参与取决于基础设施部署和利用活动。",
      panel: "支付面板",
      wallet: "钱包",
      network: "网络",
      asset: "支付资产",
      qrAmount: "二维码金额",
      receiver: "收款地址",
    },
    footer: {
      brand: "CyberCharge Node",
      disclosure:
        "本页面为前端 MVP。收益数字仅为示例，不构成财务保证。接受真实投资资金前必须提供适当法律披露。",
      mvp:
        "本 MVP 不包含后端、合约、订单系统或自动到账检测。预估利用率和部署指标仅为示例。",
    },
  },
  ja: {
    ...en,
    languageName: "日本語",
    nav: { dashboard: "ダッシュボード", nodes: "ノード", whyEv: "EVの理由", highlights: "特徴", revenue: "収益", network: "ネットワーク", payment: "支払い" },
    hero: { title: "EV充電インフラへ投資", subtitle: "実世界の配備に裏付けられた収益参加型ノード。", invest: "投資する", deployment: "配備を見る" },
    immersive: { stationTitle: "実在する充電インフラ", stationSubtitle: "実際のロケーションに配備された物理EV充電ステーション。", assetsTitle: "収益参加型エネルギー資産", assetsSubtitle: "ノード保有者は配備済みステーションの充電サービス収益に参加します。" },
    revenue: { title: "収益参加の仕組み", subtitle: "収益は配備済みステーションでの実際のEV充電活動から生まれます。", steps: ["充電ステーションをオフライン拠点へ配備します。", "EVドライバーが充電セッションに支払います。", "プラットフォームが充電サービス収益を集計します。", "収益がノード保有者へ配分されます。"] },
    infrastructure: { title: "インフラ概要", subtitle: "CyberChargeノードは、高稼働の都市環境向けに設計された共有EV充電インフラに連動します。", items: [{ title: "都市配備", description: "駐車施設、複合商業エリア、高密度の充電需要エリア向けに設計。" }, { title: "共有利用", description: "共有アクセス環境で継続的な充電活動を支えるよう最適化。" }, { title: "インフラ連動モデル", description: "収益参加は配備済みステーションの充電サービス活動に連動します。" }] },
    deployment: { ...en.deployment, title: "配備ネットワーク", subtitle: "高密度EVインフラ市場における実世界の充電ステーション配備マップ。", overview: ["計画サイト", "稼働ステーション", "配備市場", "平均推定稼働率"], selectedMarket: "選択市場", planned: "計画サイト", active: "稼働ステーション", utilization: "推定稼働率", phase: "配備フェーズ", markets: "配備市場", disclaimer: "配備データは例示であり、用地取得、許認可、設置、利用状況により変動します。" },
    payment: { ...en.payment, eyebrow: "投資入口", title: "インフラ配分", subtitle: "配備済み充電ステーションに裏付けられた分割配分ユニットを通じてEVインフラに参加します。", baseRule: "基本ルール", fullNode: "1フル充電ノード", allocation: "インフラ配分", referenceValue: "参考価値", allocationSelector: "配分選択", summary: "推定配分サマリー", ethEstimate: "ETH推定額は利用可能な場合、ライブ市場換算を使用します。", ethEstimateLive: "ETH推定額はライブ市場換算を使用し、およそ", disclaimer: "収益参加はインフラ配備と利用状況に依存します。", panel: "支払いパネル", wallet: "ウォレット", network: "ネットワーク", asset: "支払い資産", qrAmount: "QR金額", receiver: "受取アドレス" },
    why: { eyebrow: "市場背景", title: "なぜEVインフラなのか", items: [{ title: "EV普及の拡大", description: "長期的なモビリティ需要は電動フリートと個人EVへ移行しています。" }, { title: "充電需要の増加", description: "車両数の増加により、地域で利用できる充電容量が必要になります。" }, { title: "オフライン展開性", description: "共有ステーションは駐車場、小売、地域拠点へ展開できます。" }, { title: "利用収益を生む設備", description: "充電インフラは実利用を通じてサービス収益を生みます。" }] },
    features: { eyebrow: "投資ハイライト", title: "配備済みエネルギーインフラを中心に構築。", items: [{ title: "実物充電資産", description: "オフラインに配備された物理EV充電ステーションに裏付けられます。" }, { title: "収益参加モデル", description: "ノード保有者は充電サービス収益の一部に参加します。" }, { title: "Web3決済アクセス", description: "ウォレットまたはQR決済で暗号資産による購入に対応します。" }, { title: "限定配備ラウンド", description: "初期ノードは最初の配備ステーション群に関連付けられます。" }] },
    flow: { eyebrow: "投資フロー", title: "ウォレット接続からノード配分まで。", steps: [{ title: "ウォレット接続", description: "対応するWeb3ウォレットで認証します。" }, { title: "配分を選択", description: "分割インフラ配分ユニットを選択します。" }, { title: "暗号資産で支払い", description: "ETH、USDT、USDCをウォレットまたはQRで送付します。" }, { title: "配分を受領", description: "選択したノードのMVP段階の配分情報を受け取ります。" }] },
    footer: { brand: "CyberCharge Node", disclosure: "このページはフロントエンドMVPです。収益数値は例示であり、財務上の保証ではありません。実際の投資資金を受け入れる前に適切な法的開示を行ってください。", mvp: "このMVPにはバックエンド、契約、注文システム、自動入金検知は含まれません。推定稼働率と配備指標は例示です。" },
  },
  ko: {
    ...en,
    languageName: "한국어",
    nav: { dashboard: "대시보드", nodes: "노드", whyEv: "EV 인프라", highlights: "하이라이트", revenue: "수익", network: "네트워크", payment: "결제" },
    hero: { title: "EV 충전 인프라에 투자", subtitle: "실제 배포 기반의 수익 참여형 노드.", invest: "투자하기", deployment: "배포 보기" },
    immersive: { stationTitle: "실물 충전 인프라", stationSubtitle: "실제 장소에 배포되는 물리적 EV 충전소.", assetsTitle: "수익 참여형 에너지 자산", assetsSubtitle: "노드 보유자는 배포된 충전소의 서비스 수익에 참여합니다." },
    revenue: { title: "수익 참여 방식", subtitle: "수익은 배포된 충전소의 실제 EV 충전 활동에서 발생합니다.", steps: ["충전소가 오프라인 위치에 배포됩니다.", "EV 운전자가 충전 세션 비용을 지불합니다.", "플랫폼이 충전 서비스 수익을 집계합니다.", "수익이 노드 보유자에게 배분됩니다."] },
    infrastructure: { title: "인프라 개요", subtitle: "CyberCharge 노드는 고이용 도시 환경을 위해 설계된 공유 EV 충전 인프라와 연결됩니다.", items: [{ title: "도시 배포", description: "주차 시설, 복합 상업 구역, 고밀도 충전 수요 지역에 맞게 설계되었습니다." }, { title: "공유 이용", description: "공유 접근 환경에서 반복 충전 활동이 가능하도록 최적화됩니다." }, { title: "인프라 기반 모델", description: "수익 참여는 배포된 스테이션의 충전 서비스 활동과 연결됩니다." }] },
    deployment: { ...en.deployment, title: "배포 네트워크", subtitle: "고밀도 EV 인프라 시장의 실제 충전소 배포 지도.", overview: ["계획 부지", "운영 스테이션", "배포 시장", "평균 예상 이용률"], selectedMarket: "선택 시장", planned: "계획 부지", active: "운영 스테이션", utilization: "예상 이용률", phase: "배포 단계", markets: "배포 시장", disclaimer: "배포 데이터는 예시이며 부지 확보, 인허가, 설치 및 이용 활동에 따라 달라질 수 있습니다." },
    payment: { ...en.payment, eyebrow: "투자 진입", title: "인프라 배정", subtitle: "배포된 충전소 기반의 분할 배정 유닛을 통해 EV 인프라 수익 참여에 접근합니다.", baseRule: "기본 규칙", fullNode: "1개 전체 충전 노드", allocation: "인프라 배정", referenceValue: "기준 가치", allocationSelector: "배정 선택", summary: "예상 배정 요약", ethEstimate: "ETH 예상 금액은 가능할 때 실시간 시장 환산을 사용합니다.", ethEstimateLive: "ETH 예상 금액은 실시간 시장 환산 기준 약", disclaimer: "수익 참여는 인프라 배포와 이용 활동에 따라 달라집니다.", panel: "결제 패널", wallet: "지갑", network: "네트워크", asset: "결제 자산", qrAmount: "QR 금액", receiver: "수신 주소" },
    why: { eyebrow: "시장 배경", title: "왜 EV 인프라인가", items: [{ title: "EV 보급 성장", description: "장기 모빌리티 수요는 전기 플릿과 개인 EV로 이동하고 있습니다." }, { title: "충전 수요 확대", description: "도로 위 차량 증가에는 접근 가능한 지역 충전 용량이 필요합니다." }, { title: "오프라인 확장성", description: "공유 스테이션은 주차장, 리테일, 커뮤니티 부지에 배포될 수 있습니다." }, { title: "서비스 수익형 유틸리티 자산", description: "충전 인프라는 실제 사용을 통해 서비스 수익을 만듭니다." }] },
    features: { eyebrow: "투자 하이라이트", title: "배포된 에너지 인프라를 중심으로 설계.", items: [{ title: "실물 충전 자산", description: "오프라인에 배포된 물리적 EV 충전소를 기반으로 합니다." }, { title: "수익 참여 모델", description: "노드 보유자는 충전 서비스 수익의 일부에 참여합니다." }, { title: "Web3 결제 접근", description: "지갑 또는 QR 결제로 암호화폐 구매를 지원합니다." }, { title: "제한 배포 라운드", description: "초기 노드는 첫 배포 스테이션 배치와 연결됩니다." }] },
    flow: { eyebrow: "투자 흐름", title: "지갑 연결부터 노드 배정까지.", steps: [{ title: "지갑 연결", description: "지원되는 Web3 지갑으로 인증합니다." }, { title: "배정 선택", description: "분할 인프라 배정 유닛을 선택합니다." }, { title: "암호화폐 결제", description: "ETH, USDT 또는 USDC를 지갑이나 QR로 전송합니다." }, { title: "배정 수령", description: "선택한 노드의 MVP 단계 배정 정보를 받습니다." }] },
    footer: { brand: "CyberCharge Node", disclosure: "이 페이지는 프론트엔드 MVP입니다. 수익 수치는 예시이며 재무 보장이 아닙니다. 실제 투자금을 받기 전 적절한 법적 고지를 제공해야 합니다.", mvp: "이 MVP에는 백엔드, 계약, 주문 시스템 또는 자동 결제 감지가 포함되어 있지 않습니다. 예상 이용률과 배포 지표는 예시입니다." },
  },
  es: {
    ...en,
    languageName: "Español",
    nav: { dashboard: "Panel", nodes: "Nodos", whyEv: "Por qué EV", highlights: "Aspectos", revenue: "Ingresos", network: "Red", payment: "Pago" },
    hero: { title: "Invierte en infraestructura de carga EV", subtitle: "Nodos de participación en ingresos respaldados por despliegues reales.", invest: "Invertir ahora", deployment: "Ver despliegue" },
    immersive: { stationTitle: "Infraestructura de carga real", stationSubtitle: "Estaciones físicas de carga EV desplegadas en ubicaciones reales.", assetsTitle: "Activos energéticos con participación", assetsSubtitle: "Los titulares de nodos participan en ingresos de servicios de carga generados por estaciones desplegadas." },
    revenue: { title: "Cómo funciona la participación", subtitle: "Los ingresos se generan por actividad real de carga EV en estaciones desplegadas.", steps: ["Las estaciones se despliegan en ubicaciones físicas.", "Los conductores EV pagan por sesiones de carga.", "La plataforma recauda ingresos de servicio.", "Los ingresos se asignan a titulares de nodos."] },
    infrastructure: { title: "Resumen de infraestructura", subtitle: "Los nodos CyberCharge se vinculan a infraestructura compartida de carga EV diseñada para entornos urbanos de alta utilización.", items: [{ title: "Despliegue urbano", description: "Diseñado para aparcamientos, zonas comerciales mixtas y áreas de alta demanda." }, { title: "Utilización compartida", description: "Optimizado para actividad recurrente de carga en entornos de acceso compartido." }, { title: "Modelo respaldado por infraestructura", description: "La participación se vincula a la actividad de servicio de estaciones desplegadas." }] },
    deployment: { ...en.deployment, title: "Red de despliegue", subtitle: "Mapas de estaciones de carga reales en mercados EV de alta densidad.", overview: ["Sitios planificados", "Estaciones activas", "Mercados de despliegue", "Utilización estimada media"], selectedMarket: "Mercado seleccionado", planned: "Sitios planificados", active: "Estaciones activas", utilization: "Utilización estimada", phase: "Fase de despliegue", markets: "Mercados de despliegue", disclaimer: "Los datos de despliegue son ilustrativos y dependen de adquisición de sitios, permisos, instalación y utilización." },
    payment: { ...en.payment, eyebrow: "Entrada de inversión", title: "Asignación de infraestructura", subtitle: "Participa en infraestructura EV mediante unidades fraccionarias respaldadas por estaciones desplegadas.", baseRule: "Regla base", fullNode: "1 nodo completo de carga", allocation: "Asignación de infraestructura", referenceValue: "Valor de referencia", allocationSelector: "Selector de asignación", summary: "Resumen estimado", ethEstimate: "La estimación en ETH usa conversión de mercado en vivo cuando está disponible.", ethEstimateLive: "La estimación en ETH usa conversión de mercado en vivo a aproximadamente", disclaimer: "La participación en ingresos depende del despliegue y la utilización de la infraestructura.", panel: "Panel de pago", wallet: "Billetera", network: "Red", asset: "Activo de pago", qrAmount: "Importe QR", receiver: "Dirección receptora" },
    why: { eyebrow: "Contexto de mercado", title: "Por qué infraestructura EV", items: [{ title: "Crecimiento de adopción EV", description: "La demanda de movilidad se desplaza hacia flotas eléctricas y EV privados." }, { title: "Expansión de demanda de carga", description: "Más vehículos requieren capacidad de carga local accesible." }, { title: "Escalabilidad física", description: "Las estaciones compartidas pueden desplegarse en aparcamientos, retail y comunidades." }, { title: "Activos de utilidad con ingresos", description: "La infraestructura de carga crea ingresos de servicio por uso real." }] },
    features: { eyebrow: "Aspectos de inversión", title: "Construido sobre infraestructura energética desplegada.", items: [{ title: "Activos de carga reales", description: "Respaldados por estaciones físicas de carga EV desplegadas offline." }, { title: "Modelo de participación", description: "Los titulares de nodos participan en ingresos de servicios de carga." }, { title: "Acceso de pago Web3", description: "Compra nodos con crypto mediante billetera o pago QR." }, { title: "Ronda limitada", description: "Los primeros nodos se vinculan al primer lote de estaciones desplegadas." }] },
    flow: { eyebrow: "Flujo de inversión", title: "De conectar la billetera a recibir asignación.", steps: [{ title: "Conectar billetera", description: "Autentícate con una billetera Web3 compatible." }, { title: "Seleccionar asignación", description: "Elige una unidad fraccionaria de infraestructura." }, { title: "Pagar con crypto", description: "Envía ETH, USDT o USDC por billetera o QR." }, { title: "Recibir asignación", description: "Recibe detalles MVP de la asignación seleccionada." }] },
    footer: { brand: "CyberCharge Node", disclosure: "Esta página es un MVP front-end. Las cifras de ingresos son ilustrativas y no son garantías financieras. Deben existir divulgaciones legales adecuadas antes de aceptar fondos reales.", mvp: "Este MVP no incluye backend, contrato, sistema de pedidos ni detección automática de pagos. Las métricas proyectadas son solo ejemplos." },
  },
  fr: {
    ...en,
    languageName: "Français",
    nav: { dashboard: "Tableau", nodes: "Nœuds", whyEv: "Pourquoi EV", highlights: "Points clés", revenue: "Revenus", network: "Réseau", payment: "Paiement" },
    hero: { title: "Investir dans l’infrastructure de recharge EV", subtitle: "Des nœuds de participation aux revenus adossés à des déploiements réels.", invest: "Investir", deployment: "Voir le déploiement" },
    immersive: { stationTitle: "Infrastructure de recharge réelle", stationSubtitle: "Stations physiques de recharge EV déployées sur des sites réels.", assetsTitle: "Actifs énergétiques à participation", assetsSubtitle: "Les détenteurs de nœuds participent aux revenus de recharge générés par les stations déployées." },
    revenue: { title: "Fonctionnement de la participation", subtitle: "Les revenus proviennent de l’activité réelle de recharge EV sur les stations déployées.", steps: ["Les stations sont déployées sur des sites physiques.", "Les conducteurs EV paient leurs sessions de recharge.", "La plateforme collecte les revenus de service.", "Les revenus sont alloués aux détenteurs de nœuds."] },
    infrastructure: { title: "Vue d’ensemble de l’infrastructure", subtitle: "Les nœuds CyberCharge sont liés à une infrastructure partagée de recharge EV conçue pour des environnements urbains à forte utilisation.", items: [{ title: "Déploiement urbain", description: "Conçu pour parkings, zones commerciales mixtes et zones à forte demande." }, { title: "Utilisation partagée", description: "Optimisé pour une activité de recharge récurrente dans des environnements partagés." }, { title: "Modèle adossé à l’infrastructure", description: "La participation est liée à l’activité de recharge des stations déployées." }] },
    deployment: { ...en.deployment, title: "Réseau de déploiement", subtitle: "Cartes de déploiement de stations réelles dans des marchés EV à forte densité.", overview: ["Sites planifiés", "Stations actives", "Marchés de déploiement", "Utilisation estimée moyenne"], selectedMarket: "Marché sélectionné", planned: "Sites planifiés", active: "Stations actives", utilization: "Utilisation estimée", phase: "Phase de déploiement", markets: "Marchés de déploiement", disclaimer: "Les données de déploiement sont illustratives et dépendent de l’acquisition de sites, des permis, de l’installation et de l’utilisation." },
    payment: { ...en.payment, eyebrow: "Entrée d’investissement", title: "Allocation d’infrastructure", subtitle: "Participez à l’infrastructure EV via des unités fractionnées adossées à des stations déployées.", baseRule: "Règle de base", fullNode: "1 nœud complet de recharge", allocation: "Allocation d’infrastructure", referenceValue: "Valeur de référence", allocationSelector: "Sélecteur d’allocation", summary: "Résumé estimatif", ethEstimate: "L’estimation ETH utilise une conversion de marché en direct lorsqu’elle est disponible.", ethEstimateLive: "L’estimation ETH utilise une conversion de marché en direct à environ", disclaimer: "La participation aux revenus dépend du déploiement et de l’utilisation de l’infrastructure.", panel: "Panneau de paiement", wallet: "Portefeuille", network: "Réseau", asset: "Actif de paiement", qrAmount: "Montant QR", receiver: "Adresse de réception" },
    why: { eyebrow: "Contexte marché", title: "Pourquoi l’infrastructure EV", items: [{ title: "Croissance de l’adoption EV", description: "La demande de mobilité évolue vers les flottes électriques et les EV privés." }, { title: "Expansion de la demande", description: "Plus de véhicules exigent davantage de capacité de recharge locale." }, { title: "Scalabilité hors ligne", description: "Les stations partagées peuvent être déployées dans parkings, commerces et sites communautaires." }, { title: "Actifs utiles générateurs de revenus", description: "L’infrastructure de recharge crée des revenus de service par usage réel." }] },
    features: { eyebrow: "Points clés d’investissement", title: "Construit autour d’une infrastructure énergétique déployée.", items: [{ title: "Actifs de recharge réels", description: "Adossés à des stations physiques de recharge EV déployées hors ligne." }, { title: "Modèle de participation", description: "Les détenteurs de nœuds participent aux revenus des services de recharge." }, { title: "Accès paiement Web3", description: "Achetez des nœuds avec crypto via portefeuille ou paiement QR." }, { title: "Tour de déploiement limité", description: "Les premiers nœuds sont liés au premier lot de stations déployées." }] },
    flow: { eyebrow: "Parcours d’investissement", title: "De la connexion du portefeuille à l’allocation.", steps: [{ title: "Connecter le portefeuille", description: "Authentifiez-vous avec un portefeuille Web3 compatible." }, { title: "Choisir l’allocation", description: "Sélectionnez une unité fractionnée d’infrastructure." }, { title: "Payer en crypto", description: "Envoyez ETH, USDT ou USDC via portefeuille ou QR." }, { title: "Recevoir l’allocation", description: "Recevez les détails MVP de l’allocation sélectionnée." }] },
    footer: { brand: "CyberCharge Node", disclosure: "Cette page est un MVP front-end. Les chiffres de revenus sont illustratifs et ne constituent pas des garanties financières. Des informations légales appropriées sont nécessaires avant d’accepter des fonds réels.", mvp: "Ce MVP n’inclut ni backend, ni contrat, ni système de commande, ni détection automatique des paiements. Les métriques projetées sont des exemples." },
  },
  ar: {
    ...en,
    languageName: "العربية",
    nav: { dashboard: "لوحة التحكم", nodes: "العقد", whyEv: "لماذا EV", highlights: "المزايا", revenue: "الإيرادات", network: "الشبكة", payment: "الدفع" },
    hero: { title: "استثمر في بنية شحن المركبات الكهربائية", subtitle: "عقد مشاركة في الإيرادات مدعومة بعمليات نشر واقعية.", invest: "استثمر الآن", deployment: "عرض النشر" },
    immersive: { stationTitle: "بنية شحن حقيقية", stationSubtitle: "محطات شحن فعلية للمركبات الكهربائية في مواقع واقعية.", assetsTitle: "أصول طاقة بمشاركة إيرادات", assetsSubtitle: "يشارك حاملو العقد في إيرادات خدمات الشحن الناتجة عن المحطات المنشورة." },
    revenue: { title: "كيف تعمل مشاركة الإيرادات", subtitle: "تنتج الإيرادات من نشاط شحن حقيقي عبر المحطات المنشورة.", steps: ["يتم نشر محطات الشحن في مواقع فعلية.", "يدفع سائقو المركبات الكهربائية مقابل جلسات الشحن.", "تجمع المنصة إيرادات خدمة الشحن.", "تخصص الإيرادات لحاملي العقد."] },
    infrastructure: { title: "نظرة عامة على البنية", subtitle: "ترتبط عقد CyberCharge ببنية شحن مشتركة مصممة لبيئات حضرية عالية الاستخدام.", items: [{ title: "نشر حضري", description: "مصمم للمواقف والمناطق التجارية المختلطة ومناطق طلب الشحن المرتفع." }, { title: "استخدام مشترك", description: "محسن لنشاط شحن متكرر في بيئات وصول مشتركة." }, { title: "نموذج مدعوم بالبنية", description: "ترتبط المشاركة بنشاط خدمة الشحن الناتج عن المحطات المنشورة." }] },
    deployment: { ...en.deployment, title: "شبكة النشر", subtitle: "خرائط نشر لمحطات شحن واقعية في أسواق EV عالية الكثافة.", overview: ["مواقع مخططة", "محطات نشطة", "أسواق النشر", "متوسط الاستخدام التقديري"], selectedMarket: "السوق المحدد", planned: "مواقع مخططة", active: "محطات نشطة", utilization: "الاستخدام التقديري", phase: "مرحلة النشر", markets: "أسواق النشر", disclaimer: "بيانات النشر توضيحية وتخضع لاكتساب المواقع والتصاريح والتركيب ونشاط الاستخدام." },
    payment: { ...en.payment, eyebrow: "مدخل الاستثمار", title: "تخصيص البنية التحتية", subtitle: "شارك في بنية EV عبر وحدات تخصيص جزئية مدعومة بمحطات منشورة.", baseRule: "القاعدة الأساسية", fullNode: "عقدة شحن كاملة واحدة", allocation: "تخصيص البنية", referenceValue: "القيمة المرجعية", allocationSelector: "اختيار التخصيص", summary: "ملخص التخصيص التقديري", ethEstimate: "يستخدم تقدير ETH تحويل السوق المباشر عند توفره.", ethEstimateLive: "يستخدم تقدير ETH تحويل السوق المباشر عند نحو", disclaimer: "تعتمد مشاركة الإيرادات على نشر البنية ونشاط الاستخدام.", panel: "لوحة الدفع", wallet: "المحفظة", network: "الشبكة", asset: "أصل الدفع", qrAmount: "مبلغ QR", receiver: "عنوان الاستلام" },
    why: { eyebrow: "سياق السوق", title: "لماذا بنية EV", items: [{ title: "نمو اعتماد EV", description: "يتحول طلب التنقل طويل الأجل نحو الأساطيل الكهربائية والمركبات الخاصة." }, { title: "توسع طلب الشحن", description: "تحتاج المركبات الإضافية إلى سعة شحن محلية يسهل الوصول إليها." }, { title: "قابلية التوسع الميداني", description: "يمكن نشر المحطات المشتركة في المواقف والتجزئة والمواقع المجتمعية." }, { title: "أصول خدمية مولدة للإيرادات", description: "تنشئ بنية الشحن إيرادات خدمة من الاستخدام الواقعي." }] },
    features: { eyebrow: "أبرز نقاط الاستثمار", title: "مبني حول بنية طاقة منشورة.", items: [{ title: "أصول شحن واقعية", description: "مدعومة بمحطات شحن EV فعلية منشورة ميدانيا." }, { title: "نموذج مشاركة الإيرادات", description: "يشارك حاملو العقد في جزء من إيرادات خدمة الشحن." }, { title: "وصول دفع Web3", description: "شراء العقد بالعملات الرقمية عبر المحفظة أو QR." }, { title: "جولة نشر محدودة", description: "ترتبط العقد المبكرة بأول دفعة من المحطات المنشورة." }] },
    flow: { eyebrow: "مسار الاستثمار", title: "من اتصال المحفظة إلى تخصيص العقدة.", steps: [{ title: "اتصال المحفظة", description: "المصادقة بمحفظة Web3 مدعومة." }, { title: "اختيار التخصيص", description: "اختر وحدة تخصيص بنية جزئية." }, { title: "الدفع بالعملات الرقمية", description: "أرسل ETH أو USDT أو USDC عبر المحفظة أو QR." }, { title: "استلام التخصيص", description: "استلم تفاصيل تخصيص مرحلة MVP للعقدة المحددة." }] },
    footer: { brand: "CyberCharge Node", disclosure: "هذه الصفحة نموذج MVP للواجهة الأمامية. أرقام الإيرادات توضيحية وليست ضمانات مالية. يجب تقديم إفصاحات قانونية مناسبة قبل قبول أموال استثمار حقيقية.", mvp: "لا يتضمن هذا النموذج خلفية أو عقدا أو نظام طلبات أو كشف دفع تلقائي. مقاييس الاستخدام والنشر المتوقعة أمثلة فقط." },
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: Translation;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const dir: "ltr" | "rtl" = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [dir, language]);

  const value = useMemo(
    () => ({ language, setLanguage, t: translations[language], dir }),
    [dir, language],
  );

  return createElement(LanguageContext.Provider, { value }, children);
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}
